on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: appleboy/ssh-action@v0.1.9

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo ${{ secrets.HOST }}
            sudo cp -R ./FirstProject/FirstProject.html /var/www/html/

