on:
 push:
    branches:
      - main
 pull_request:
    branches:
      - main
 workflow_dispatch:
  
jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts

      - name: Copy files to server
        run: |
          ssh -v ${{ secrets.USERNAME }}@${{ secrets.IP }}

