on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.IP }} > ~/.ssh/known_hosts

      - name: Copy files to server
        run: |
          ssh -i ~/.ssh/id_rsa -o PasswordAuthentication=no -v ${{ secrets.USERNAME }}@${{ secrets.IP }}
        env:
          SSH_AUTH_SOCK: ${{ secrets.SSH_AUTH_SOCK }}
